version: 0.2 
 
environment_variables: 
  plaintext: 
    HUGO_VERSION: "0.55.4" 
    HUGO_SHA256: "fca0223d05e6bf9992a2050480635ea73fe1633ebab0c64b4fe991d0dbc7a0af" 
     
phases: 
  install: 
    commands: 
      - curl -Ls https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz 
      - echo "${HUGO_SHA256}  /tmp/hugo.tar.gz" | sha256sum -c - 
      - tar xf /tmp/hugo.tar.gz -C /tmp 
      - mv /tmp/hugo /usr/bin/hugo 
      - rm -rf /tmp/hugo*
      - bash retrieveTimeStamps.sh
  pre_build: 
    commands: 
      - rm -rf /tmp/hugo_cache/ 
      - rm -rf ./public 
  build: 
    commands: 
      - HUGO_ENV=production hugo --ignoreCache 
  post_build: 
    commands: 
      - aws --region ap-south-1 s3 sync --exclude '*' --include 'index.html' --cache-control 'max-age=300' --acl public-read public/ s3://blog.spuul.com/ 
      - aws --region ap-south-1 s3 sync --exclude 'index.html' --cache-control 'max-age=43200' --acl public-read public/ s3://blog.spuul.com/